### ISSUE TITLE
Is the predicting parameters of each primitive is independent from the other primitives

### ISSUE THREAD

**Issue by mahmoudEltaher** [paschalidoud/superquadric_parsing#16]
Dears,

Kindly, i want to inquire about 
Is the predicting parameters of each primitive is independent from the other primitives,which means is the parameters of each primitive is independent of each other or not.how all these primitives are combined together to determine the full shape.

why the model predict primitives and at final all these primitives combines the shape,what prevent the model to predict the same primitive each time ?

why the primitives is attached to each other,what force this behavior in the prediction process

**Comment by paschalidoud** [comment]
Hello,

Each primitive depends on the others both in terms of their prediction (they are predicted from the same intermediate representation) and in terms of the loss (each primitive influences the loss for the rest of the primitives).

Regarding how the primitives are combined to form the whole shape, this is precisely what the loss enforces. For more details regarding the optimization objective please have a look at the paper
[https://superquadrics.com/learnable-superquadrics.html](https://superquadrics.com/learnable-superquadrics.html)

Since this question is not related to the code release I am closing the issue for now.

Best,
Despoina
